version: '3.8'

services:

  emailing-service:
    image: 'ghcr.io/ozon-edu-csharp-2021/emailing-service:main'
    hostname: emailing-service

  employees-service:
    image: 'ghcr.io/ozon-edu-csharp-2021/employees-service:main'
    hostname: employees-service

  stock-api:
    image: 'ghcr.io/ozon-edu-csharp-2021/stock-api:main'
    hostname: stock-api
    ports:
      - "8080:80"

  supply-service:
    image: 'ghcr.io/ozon-edu-csharp-2021/supply-service:main'
    hostname: supply-service
    depends_on:
      - stock-api

  merchandise-service:
    image: 'ghcr.io/ozon-edu-csharp-2021/stock-api:main'
    hostname: stock-api
    depends_on:
      - stock-api